export enum EBrandActions {
  GET_BRANDS = 'GET_BRANDS',
  CREATE_BRAND = 'CREATE_BRAND',
  UPDATE_BRAND = 'UPDATE_BRAND',
  UPDATE_BRAND_LOGO = 'UPDATE_BRAND_LOGO',
  TOGGLE_BRAND_STATUS = 'TOGGLE_BRAND_STATUS',
  DELETE_BRAND = 'DELETE_BRAND',
}
