export enum EProductActions {
  GET_PRODUCTS = 'GET_PRODUCTS',
  GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL',
  CREATE_PRODUCT = 'CREATE_PRODUCT',
  TOGGLE_PRODUCT_STATUS = 'TOGGLE_PRODUCT_STATUS',
  DELETE_PRODUCT = 'DELETE_PRODUCT',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
}
